import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import Link from "next/link";
import React from "react";
import LoginBar from "~/app/_components/LoginBar";
import { Providers } from "~/app/providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <Providers>
          <nav className="flex items-center justify-between bg-green-600 px-8 py-5 lg:px-16">
            <div className="flex gap-4">
              <Link href="/">Home</Link>
              <Link href="/about">About us</Link>
            </div>
            <LoginBar />
          </nav>
          <TRPCReactProvider headers={headers()}>{children}</TRPCReactProvider>
        </Providers>
      </body>
    </html>
  );
}
